<?php

namespace App\Http\Controllers\Kecamatan;

use App\Http\Controllers\Controller;
use App\Models\Umkm;
use App\Models\UmkmAdminLog;
use App\Models\Desa;
use App\Models\PublicService;
use App\Models\WorkDirectory;
use App\Traits\HasWhatsAppNotifications;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class LayananPublikController extends Controller
{
    use HasWhatsAppNotifications;
    /**
     * --- UMKM RAKYAT FACILITATOR SECTION ---
     * Menggantikan fungsi UMKM lama dengan sistem UMKM Rakyat.
     */

    public function umkmIndex(Request $request)
    {
        $activeTab = $request->query('tab', 'umkm');
        $q = $request->query('q');

        $umkm = null;
        $jasa = null;

        if ($activeTab == 'umkm') {
            $query = Umkm::latest();
            if ($q) {
                $query->where('nama_usaha', 'like', '%' . $q . '%')
                    ->orWhere('nama_pemilik', 'like', '%' . $q . '%');
            }
            $umkm = $query->paginate(10)->appends($request->all());
        } else {
            $query = WorkDirectory::latest();
            if ($q) {
                $query->where('display_name', 'like', '%' . $q . '%')
                    ->orWhere('job_title', 'like', '%' . $q . '%');
            }
            $jasa = $query->paginate(10)->appends($request->all());
        }

        return view('kecamatan.layanan.umkm.index', compact('umkm', 'jasa', 'activeTab'));
    }

    public function umkmCreate(Request $request)
    {
        // Form "Bantu Daftarkan UMKM"
        $desas = Desa::orderBy('nama_desa')->get();

        // Auto-fill dari inbox (jika ada)
        $prefill = [
            'from_inbox' => $request->query('from_inbox'),
            'nama_pemilik' => $request->query('nama'),
            'no_wa' => $request->query('wa'),
            'desa' => $request->query('desa') ? Desa::find($request->query('desa'))?->nama_desa : null,
        ];

        return view('kecamatan.layanan.umkm.form_bantuan', compact('desas', 'prefill'));
    }

    public function umkmStore(Request $request)
    {
        $validated = $request->validate([
            'nama_usaha' => 'required|string|max:255',
            'nama_pemilik' => 'required|string|max:255',
            'no_wa' => 'required|string|max:20', // Format 62...
            'jenis_usaha' => 'required|string|max:100',
            'desa' => 'required|string',
            'notes' => 'nullable|string',
            'nib_number' => 'nullable|string|max:50',
            'is_verified' => 'nullable|boolean',
        ]);

        // Create UMKM
        $umkm = new Umkm();
        $umkm->nama_usaha = $validated['nama_usaha'];
        $umkm->nama_pemilik = $validated['nama_pemilik'];
        $umkm->no_wa = $validated['no_wa'];
        $umkm->jenis_usaha = $validated['jenis_usaha'];
        $umkm->desa = $validated['desa'];
        $umkm->is_verified = $request->boolean('is_verified');
        $umkm->nib_number = $validated['nib_number'] ?? null;

        // System fields
        $umkm->source = Umkm::SOURCE_ADMIN; // created_by kecamatan
        $umkm->status = Umkm::STATUS_AKTIF; // Langsung aktif agar bisa langsung dikelola, tapi butuh handover
        $umkm->ownership_status = 'pending_transfer'; // Menunggu warga ambil alih via link

        $umkm->save(); // Slug & Token generated by Model Boot

        // Log Action
        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'create',
            'actor' => 'admin', // Kecamatan
            'notes' => 'Pendaftaran jalur bantuan (Fasilitator). ' . ($validated['notes'] ?? ''),
        ]);

        // Automate Inbox Sync
        if ($request->filled('from_inbox')) {
            $inbox = PublicService::find($request->from_inbox);
            if ($inbox) {
                $inbox->update([
                    'status' => PublicService::STATUS_SELESAI,
                    'public_response' => "Lapak UMKM Anda ({$umkm->nama_usaha}) telah terdaftar dan aktif. Silakan kelola melalui link yang dikirimkan petugas atau via WhatsApp.",
                    'handled_by' => auth()->id(),
                    'handled_at' => now(),
                    'responded_at' => now(),
                ]);
                // Trigger notification for the inbox closure
                $this->sendWaNotification($inbox, 'status_update');
            }
        }

        // Redirect to Handover Page
        return redirect()->route('kecamatan.umkm.handover', $umkm->id)
            ->with('success', 'UMKM berhasil didaftarkan. Segera lakukan serah terima digital.');
    }

    public function umkmHandover($id)
    {
        $umkm = Umkm::findOrFail($id);

        // Generate Link
        $manageLink = route('umkm_rakyat.manage', $umkm->manage_token);

        // WhatsApp Message generator
        $waMessage = "Halo {$umkm->nama_pemilik},\n\n";
        $waMessage .= "Berikut adalah link akses untuk mengelola Lapak UMKM Anda ({$umkm->nama_usaha}).\n\n";
        $waMessage .= "Silakan klik link ini untuk mulai melengkapi produk dan foto:\n";
        $waMessage .= $manageLink . "\n\n";
        $waMessage .= "Simpan link ini baik-baik. Jangan berikan kepada orang lain.";

        $waUrl = "https://wa.me/{$umkm->no_wa}?text=" . urlencode($waMessage);

        return view('kecamatan.layanan.umkm.handover', compact('umkm', 'manageLink', 'waUrl', 'waMessage'));
    }

    public function umkmEdit($id)
    {
        $umkm = Umkm::findOrFail($id);
        $desas = Desa::orderBy('nama_desa')->get();
        return view('kecamatan.layanan.umkm.edit_admin', compact('umkm', 'desas'));
    }

    public function umkmUpdate(Request $request, $id)
    {
        $umkm = Umkm::findOrFail($id);

        $validated = $request->validate([
            'nama_usaha' => 'required|string|max:255',
            'nama_pemilik' => 'required|string|max:255',
            'no_wa' => 'required|string|max:20',
            'jenis_usaha' => 'required|string',
            'desa' => 'required|string',
            'nib_number' => 'nullable|string|max:50',
            'is_verified' => 'nullable|boolean',
        ]);

        $validated['is_verified'] = $request->boolean('is_verified');
        $umkm->update($validated);

        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'verify',
            'actor' => 'admin',
            'notes' => 'Koreksi data administratif oleh kecamatan.',
        ]);

        return redirect()->route('kecamatan.umkm.index')->with('success', 'Data administratif UMKM diperbarui.');
    }

    public function umkmDestroy($id)
    {
        $umkm = Umkm::findOrFail($id);
        $umkm->delete();

        return redirect()->route('kecamatan.umkm.index')->with('success', 'UMKM dinonaktifkan/dihapus.');
    }

    public function resetAkses($id)
    {
        $umkm = Umkm::findOrFail($id);
        $umkm->manage_token = Str::random(40);
        $umkm->save();

        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => 'activate',
            'actor' => 'admin',
            'notes' => 'Reset akses (Token baru) atas permintaan warga.',
        ]);

        return redirect()->route('kecamatan.umkm.handover', $umkm->id)
            ->with('success', 'Akses UMKM berhasil di-reset. Silakan berikan link baru.');
    }

    /**
     * --- JASA & TENAGA FACILITATOR SECTION ---
     */

    public function jasaCreate(Request $request)
    {
        $desas = Desa::orderBy('nama_desa')->get();
        $categories = WorkDirectory::getCategories();
        
        $prefill = [
            'from_inbox' => $request->query('from_inbox'),
            'display_name' => $request->query('nama'),
            'contact_phone' => $request->query('wa'),
            'service_area' => $request->query('desa') ? Desa::find($request->query('desa'))?->nama_desa : null,
        ];

        return view('kecamatan.layanan.umkm.jasa_form', compact('desas', 'categories', 'prefill'));
    }

    public function jasaStore(Request $request)
    {
        $validated = $request->validate([
            'display_name' => 'required|string|max:255',
            'job_title' => 'required|string|max:255',
            'job_category' => 'required|string',
            'contact_phone' => 'required|string|max:20',
            'service_area' => 'required|string',
            'job_type' => 'required|in:jasa,transportasi,keliling,harian',
            'is_verified' => 'nullable|boolean',
        ]);

        $jasa = WorkDirectory::create($validated + [
            'status' => 'active',
            'data_source' => 'admin',
            'consent_public' => true,
            'is_verified' => $request->boolean('is_verified'),
        ]);

        // Automate Inbox Sync
        if ($request->filled('from_inbox')) {
            $inbox = PublicService::find($request->from_inbox);
            if ($inbox) {
                $inbox->update([
                    'status' => PublicService::STATUS_SELESAI,
                    'public_response' => "Layanan Jasa Anda ({$jasa->job_title}) telah terdaftar. Silakan kelola melalui link yang dikirimkan.",
                    'handled_by' => auth()->id(),
                    'handled_at' => now(),
                    'responded_at' => now(),
                ]);
                $this->sendWaNotification($inbox, 'status_update');
            }
        }

        return redirect()->route('kecamatan.jasa.handover', $jasa->id)
            ->with('success', 'Jasa berhasil didaftarkan.');
    }

    public function jasaHandover($id)
    {
        $jasa = WorkDirectory::findOrFail($id);
        $manageLink = route('portal_warga.login'); // Generic portal link for services

        $waMessage = "Halo {$jasa->display_name},\n\n";
        $waMessage .= "Berikut adalah link akses untuk mengelola Jasa Anda ({$jasa->job_title}).\n\n";
        $waMessage .= "Silakan login menggunakan nomor WhatsApp Anda di:\n";
        $waMessage .= $manageLink . "\n\n";
        
        $waUrl = "https://wa.me/{$jasa->contact_phone}?text=" . urlencode($waMessage);

        return view('kecamatan.layanan.umkm.jasa_handover', compact('jasa', 'manageLink', 'waUrl', 'waMessage'));
    }

    public function jasaEdit($id)
    {
        $jasa = WorkDirectory::findOrFail($id);
        $desas = Desa::orderBy('nama_desa')->get();
        $categories = WorkDirectory::getCategories();
        return view('kecamatan.layanan.umkm.jasa_edit', compact('jasa', 'desas', 'categories'));
    }

    public function jasaUpdate(Request $request, $id)
    {
        $jasa = WorkDirectory::findOrFail($id);
        $validated = $request->validate([
            'display_name' => 'required|string|max:255',
            'job_title' => 'required|string|max:255',
            'job_category' => 'required|string',
            'contact_phone' => 'required|string|max:20',
            'service_area' => 'required|string',
            'status' => 'required|in:active,inactive',
        ]);

        $jasa->update($validated);

        return redirect()->route('kecamatan.umkm.index', ['tab' => 'jasa'])->with('success', 'Data Jasa diperbarui.');
    }

    public function jasaDestroy($id)
    {
        $jasa = WorkDirectory::findOrFail($id);
        $jasa->delete();

        return redirect()->route('kecamatan.umkm.index', ['tab' => 'jasa'])->with('success', 'Jasa dinonaktifkan.');
    }

    public function jasaResetAkses($id)
    {
        $jasa = WorkDirectory::findOrFail($id);
        $jasa->manage_token = Str::random(40);
        $jasa->save();

        return redirect()->route('kecamatan.jasa.handover', $jasa->id)
            ->with('success', 'Akses Jasa di-reset.');
    }

    public function umkmToggleVerify($id)
    {
        $umkm = Umkm::findOrFail($id);
        $umkm->is_verified = !$umkm->is_verified;
        $umkm->save();

        $status = $umkm->is_verified ? 'diverifikasi (Centang Biru aktif)' : 'batal diverifikasi';

        UmkmAdminLog::create([
            'umkm_id' => $umkm->id,
            'action' => $umkm->is_verified ? 'verify' : 'deactivate',
            'actor' => 'admin',
            'notes' => "Unit usaha {$status} oleh kecamatan.",
        ]);

        return back()->with('success', "UMKM {$umkm->nama_usaha} berhasil {$status}.");
    }

    public function jasaToggleVerify($id)
    {
        $jasa = WorkDirectory::findOrFail($id);
        $jasa->is_verified = !$jasa->is_verified;
        $jasa->save();

        $status = $jasa->is_verified ? 'diverifikasi (Centang Biru aktif)' : 'batal diverifikasi';

        return back()->with('success', "Jasa {$jasa->job_title} berhasil {$status}.");
    }
}
