services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-gateway
    restart: always
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=benchoaz@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
      - ./acme.json:/acme.json
    networks:
      - kecamatan-network

networks:
  kecamatan-network:
    external: true
